### ISSUE TITLE
Any way to delete a fork?

### ISSUE THREAD

**Issue by vetmiker** [emu-sh/.oh-my-comma#44]
I mistakenly cloned "https://github.com/dragonpilot" instead of "https://github.com/dragonpilot-**community**/dragonpilot

What's the best way to delete the fork?

**Comment by ShaneSmiskol** [comment]
Did you clone it with git pull or used the fork manager to switch to it? If you used emu, you don't necessarily need to delete the remote/fork for anything to be resolved, just switch away from it.

**Comment by vetmiker** [comment]
I used the fork manager to pull it in. It's related to the other issue with Dragonpilot cloning - so as long as the fix for that doesn't mess this one up, I could just leave it in there.

**Comment by AskAlice** [comment]
Check this out if you want to do some cleanup within git.

https://stackoverflow.com/questions/4890772/how-to-remove-remote-origin-refs-heads-master#4891167

**Comment by AskAlice** [comment]
We can consider adding this functionality but for now, the answer is use git.
