### ISSUE TITLE
Initial install of emu sh/ oh my comma on a C3 installs release2 and not release3

### ISSUE THREAD

**Issue by nelsonjchen** [emu-sh/.oh-my-comma#66]

**Comment by sshane** [comment]
Would you like to make a simple PR for this? It should be very similar to the fork installer

**Comment by nelsonjchen** [comment]
Sure

**Comment by nelsonjchen** [comment]
Delayed due to having to lend out my C3 for toyota security stuff. Up for grabs if anyone else wants to get to it before my C3 gets back to me.

**Comment by nelsonjchen** [comment]
I have my C3 back. I might get to this.

**Comment by nelsonjchen** [comment]
Ah, I haven't been using this enough to try to add support for this. If someone else wants to try a stab at it, be my guest.

**Comment by sshane** [comment]
Fixed by https://github.com/emu-sh/.oh-my-comma/pull/67
